### ISSUE TITLE
Conjur Helm Chart exposes CONJUR_AUTHENTICATORS

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/conjur-oss-helm-chart#10]
When using the Helm chart to deploy Conjur, there is no way to set the `CONJUR_AUTHENTICATORS` variable.  This means we can't configure Conjur to for Authn-K8s.

**Expected Behavior**
We should be able to set `CONJUR_AUTHENTICATORS` so that users can use authn-k8s, or any other authenticator.

Estimate: 1 day
Confidence: high

**Comment by sgnn7** [comment]
https://github.com/cyberark/conjur-oss-helm-chart/pull/14
