### ISSUE TITLE
Update GCP with new helm chart

### ISSUE THREAD

**Issue by ismarc** [cyberark/conjur-oss-helm-chart#13]
The Google Marketplace needs to be updated with the new helm chart.

From the onboarding document provided by google:

> The process for updating your solution is very similar to initial onboarding. First, generate a new set of container images and push them to your staging repository. Then, contact your Cloud Launcher Partner Engineer to begin submission and review of a new version.
>
>Once published, the new version will become the default for new customers. Existing customers will see new images pushed to existing tags. UI installations are always pinned to image digests and will not be automatically updated. We are recommending the same to customers performing CLI installation. You should provide instructions in your ​user guide​ for upgrading application images.

When the images are pushed, we should increment the tag and include that information in the request.

depends on #10 [x]
depends on #11 [ ]

**Comment by sgnn7** [comment]
Blocked on Google engineers to give us a staging endpoint per email thread.

**Comment by sgnn7** [comment]
This is released now: https://console.cloud.google.com/marketplace/details/cyberark/conjur-open-source has tag v1.3
