### ISSUE TITLE
Conjur Helm Chart Deploys the Database as Persistent

### ISSUE THREAD

**Issue by RafiS3** [cyberark/conjur-oss-helm-chart#15]
Currently the PostgreSQL instance which is deployed as part of Conjur OSS, is not persistent. This means that as soon as the database container stops, all the data in it is lost.

**Expected Behavior**
The Conjur Helm chart should expose a new parameter that can toggle the deployment of PostgreSQL as persistent. We can use this [link](https://severalnines.com/blog/using-kubernetes-deploy-postgresql) as a reference.

**Comment by dsbyrne** [comment]
Added in `v1.3.5` (3682682)
