### ISSUE TITLE
Repository has a valid pipeline

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-oss-helm-chart#32]
This repository was running a Gitlab pipeline that is no longer functioning as originally designed, and there is no Jenkins pipeline for the project.

The Gitlab pipeline needs to be converted to a Jenkins pipeline so that automated tests can continue to run for this project.

**Comment by JakeQuilty** [comment]
When pipeline is created, add Validate step to Jenkinsfile.
Ex: https://github.com/cyberark/conjur-oss-helm-chart/issues/38

**Comment by izgeri** [comment]
This was fixed in #51
