### ISSUE TITLE
Fix usage of `docs-release` templating

### ISSUE THREAD

**Issue by sgnn7** [cyberark/conjur-oss-helm-chart#50]
## Summary

Currently when we use html templates, they are not using `html/template` package but `text/template` and thus not loading the partials either. 

## Steps to Reproduce

- Run `./parse-changelogs -t docs-release`

## Expected Results

All output should follow [`html/template`](https://golang.org/pkg/html/template/) pattern where needed

## Actual Results (including error logs, if applicable)

Output uses plain `text/template` transformation

## Acceptance Criteria

- [ ] Ensure html templates use the proper template package
- [ ] Ensure html partials can work in integration test(s)
- [ ] Ensure that (if merged at that time) installation instructions for Conjur are moved to a partial

**Comment by izgeri** [comment]
Filed in wrong repo - moved to https://github.com/cyberark/conjur-oss-suite-release/issues/205
