### ISSUE TITLE
Support helm chart on OCP

### ISSUE THREAD

**Issue by guygiat** [cyberark/conjur-oss-helm-chart#60]
## Summary
Today our helm chart doesn't support OCP because we require the conjur image to run as root and therefore to enable anyuid permission to the SA that will run the conjur deployment.

## Expected Results
Install Conjur using helm chart on OCP 3.x 4.x

## Additional Information
Our new container-dap project already have the fixes required to run without root.
We can take the fixes from the container-dap project and port them to the OSS project.

**Comment by izgeri** [comment]
Just noting that before we can merge this, we have to complete these issues:
- cyberark/conjur#1871
- cyberark/conjur#1883
- cyberark/conjur-base-image#25
- cyberark/conjur-base-image#28

**Comment by izgeri** [comment]
Also, once this is done we can complete #115
