### ISSUE TITLE
Flakey CI builds

### ISSUE THREAD

**Issue by sgnn7** [cyberark/conjur-oss-helm-chart#73]
## Summary
CI daily builds seem to have frequent failures from flaky tests.

## Steps to Reproduce
1. Go to https://jenkins.conjur.net/job/cyberark--conjur-oss-helm-chart/job/master/
2. See unstable results

## Expected Results

Green builds

## Actual Results (including error logs, if applicable)

Sporadic failures

## Reproducible
   * [ ] Always 
   * [x] Sometimes
   * [ ] Non-Reproducible
   
## Version/Tag number

Latest/`master`

## Environment setup

Jenkins

## Additional Information
N/A

**Comment by diverdane** [comment]
Looks like the cluster bringup used to take about 2 minutes consistently, and now it's taking ~3 minutes, which is what our wait-for-Conjur time is set for. That is, looks like we may be on the hairy edge of working in time. I'm wondering if we're being affected by image pull times.

- [Build #62](https://jenkins.conjur.net/job/cyberark--conjur-oss-helm-chart/job/master/62/console) failed waiting for Conjur server at 3 minutes.
- For [Build #63](https://jenkins.conjur.net/job/cyberark--conjur-oss-helm-chart/job/master/63/console), Conjur server came up right at the brink of 3 minutes, but then the Helm test failed 5 minutes later.

**Comment by izgeri** [comment]
I added this to the epic I'm creating to track broken / flaky builds, but I'm not sure this is still relevant?

**Comment by izgeri** [comment]
@diverdane is this still relevant, or can it be closed?

**Comment by izgeri** [comment]
Closing, as this no longer seems to be an issue.
