### ISSUE TITLE
End-to-End UX and Documentation Updates for authn-k8s on Conjur-OSS is Perfomed

### ISSUE THREAD

**Issue by diverdane** [cyberark/conjur-oss-helm-chart#74]
# Kubernetes authn-k8s Authentication on Conjur-OSS

This epic tracks efforts to do an End-to-End UX test on deploying applications that use authn-k8s authentication on Kubernetes platforms using Conjur clusters that have been deployed via the Conjur OSS Helm charts. Included in this work is an audit of any documentation related to configuring Conjur for authn-k8s authentication and deploying applications that use various authentication clients, including Secretless broker, authn-k8s side car containers, and authn-k8s init containers.

Currently, there are two main methods of configuring application identity for authn-k8s:
- (Old style) Host-ID-based app identity, where the Kubernetes resource (e.g. ServiceAccount, Deployment,
   Namespace, etc) to be authenticated is included in the Conjur policy host ID using the suffix
   `<namespace>.<k8s-resource-type>.<k8s-resource-name>` in the authentication path.
- Annotation-based app identity (new style), where the host ID in the policy is an application name, and the
   specific Kubernetes resource to use for authentication is configured in the policy as an annotation
   on that applicationhost.
   included in the policy 

Wherever practical, this epic will also include updates to automated integration tests to test various combinations of Kubernetes platforms, authentication workflows, and authentication clients.

# Project Scope

## In Scope
- Identify user pain points and documentation gaps while setting up applications using authn-k8s with Conjur-OSS clusters:
   - Platforms: GKE, OpenShift, KinD
   - Application identity schemes/workflows: host-ID based app identity, annotation-based
   - Authentication clients: Secretless Broker, authn-k8s sidecar, authn-k8s init container
- Deprecation of host-ID-based authentication: Update any documentation that currently uses host-ID
   based authentication to use annotation-based authentication.
- Enhance Conjur OSS Helm chart documentation to include examples of how to run applications that use authn-k8s
- Add troubleshooting documentation for debugging authn-k8s
- Wherever practical, add automated integration tests (Jenkins or Github actions based) for testing authn-k8s on Conjur-OSS
- After any changes are made to Conjur or demo scripts, test authn-k8s on Conjur DAP/appliance to check for regressions. 

## Out of Scope

# Project Value Overview
- There have been many community issues filed involving using authn-k8s on Conjur-OSS. This is an obvious pain point.
- Setting up a "sandbox" to replicate issues involving authn-k8s is currently laborious and error-prone.

**Comment by InbalZilberman** [comment]
A lot of work was done to remove host-ID-based authentication from the docs. Did you find places where it is mentioned?

**Comment by izgeri** [comment]
@InbalZilberman yes, it was mentioned in the Secretless docs. We're working with the technical writers to update this.
