### ISSUE TITLE
Documentation includes instructions for using `helm upgrade` to update environment variables

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-oss-helm-chart#75]
GIVEN I have deployed Conjur OSS using the helm chart
AND I want to add or modify an environment variable in the Conjur container
THEN when I come to the helm chart README, there are clear instructions for modifying the Conjur environment variables
AND to modify the Conjur environment variables, I don't have to tear down my existing deployment and start a new one from scratch

**Comment by diverdane** [comment]
This has been addressed with PR #79 "Add logLevel for Conjur container".  The logLevel is used as an example as to how to use `helm upgrade ...` to modify Conjur container/pod environment variables.
